# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Buyer(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    first_name: str | None = None
    """
    First name of the buyer.
    """
    last_name: str | None = None
    """
    Last name of the buyer.
    """
    email: str | None = None
    """
    Email of the buyer.
    """
    phone_number: str | None = None
    """
    E.164 standard.
    """
