# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import ConfigDict

from .payment_credential import PaymentCredential


class TokenCredential(PaymentCredential):
    """
    Base token credential schema. Concrete payment handlers may extend this schema with additional fields and define their own constraints.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: str
    """
    The specific type of token produced by the handler (e.g., 'stripe_token').
    """
    token: str
    """
    The token value.
    """
